### ISSUE TITLE
求一个本地部署教程

### ISSUE THREAD

**Issue by Sliccic** [Huli-fox/bili-live-heart#19]
这个跟原版那个用的同一个文档，所以部署起来不太会，总是出各种各样的问题还没法排查，可以出一个详细点的教程嘛？主要是云函数不能使用了，迫不得已用本地部署

**Comment by Huli-fox** [comment]
非常抱歉给你带来不便
近日事务繁杂，这两天我尽力出好教程

**Comment by Sliccic** [comment]
非常感谢，我已解决问题，但是更多的人需要这个教程，麻烦你了！

**Comment by Huli-fox** [comment]
> 非常感谢，我已解决问题，但是更多的人需要这个教程，麻烦你了！

[教程](https://github.com/Huli-fox/bili-live-heart/tree/morepush#%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8)
新鲜出炉
有问题欢迎再提~
