### ISSUE TITLE
推送失败

### ISSUE THREAD

**Issue by Allroha** [Huli-fox/bili-live-heart#20]
2022-04-27 12:51:28,321 - pushaio - INFO - 正在准备发送通知...
TG没收到推送结果

onepush = '{"notifier":"telegram","params":{"markdown":True,"token":"xxx","userid":"xxx"}}'

没填错吧🤔

**Comment by Huli-fox** [comment]
检查下“网络环境”：本地部署需要代理，云函数部署需要切换地区至香港  
  
另：markdown参数大小写敏感，把T改成小写试试  "markdown":true  
看了下我文档里最后一句话也打成大写了，产生歧义我非常抱歉

**Comment by Allroha** [comment]
> 

我是在国外VPS跑的

小写情况：NameError: name 'true' is not defined
只有大写才能运行，这次有推送了

**Comment by Huli-fox** [comment]
问题解决了就好（
至于大小写这个锅得让onepush作者背，他官方文档里给的例子就是小写（
我修正下文档，有问题可以再提
